### ISSUE TITLE
Git - Fix branch but not a hotfix

### ISSUE THREAD

**Issue by navvyua** [ergoserv/handbook#10]
What about long-term fixes which are not "hot"? Currently, I'm doing something like `feature/1234-fix-inmate-updating`, maybe we can have a `fix` namespace? So `fix/1234-inmate-updating`.

**Comment by stgeneral** [comment]
These prefixes aim to describe the flow for the branch more than its' content. Hotfix branches - are for emergency cases and may have a shorter or quicker delivery path, while feature branches follow the regular flow. 

More details about these branches: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow and https://nvie.com/posts/a-successful-git-branching-model/.

**Comment by navvyua** [comment]
Ok, I see, thanks!
